spring.application.name=iMebel

#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/i_mebel
spring.datasource.username=postgres
spring.datasource.password=xush2004@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#server configuration
server.port=8080

#jwt configuration
jwt.secret.key="qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvtrghbtrbrtbntrnrtgwnwrnwnbnm"
jwt.expiration=3600000

#spring mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support.imebel@gmail.com
spring.mail.password=lwna zcmn jmxi impo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#redis configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

#Cloudinary configuration
cloudinary.cloud-name=dsx12v4h6
cloudinary.api-key=538666728948165
cloudinary.api-secret=JlniB9YI2q9UGjhchfPAscoAwfA