spring.application.name=iMebel

# Server
server.port=${PORT:8080}

# Database (ENV dan oladi)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

#jwt configuration
jwt.secret.key="qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvtrghbtrbrtbntrnrtgwnwrnwnbnm"
jwt.expiration=3600000

#spring mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=support.imebel@gmail.com
spring.mail.password=lwna zcmn jmxi impo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#redis configuration

#Cloudinary configuration
cloudinary.cloud-name=dsx12v4h6
cloudinary.api-key=538666728948165
cloudinary.api-secret=JlniB9YI2q9UGjhchfPAscoAwfA

#flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true